version: '3'

services:
    db:
        image: postgres
    web:
        build: .
        command: bash -c "npm install && npm run start:server"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "8080:8080"
            - "3000:3000"
        depends_on:
            - db
